name: match_case
description: A dart package for pattern matching.
version: 0.0.4
homepage: https://github.com/sabinbajracharya/match_case

environment:
  sdk: ">=2.15.1 <3.0.0"
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
