name: match_case
description: A dart package for pattern matching.
version: 0.0.3
homepage: https://github.com/sabinbajracharya/match_case

environment:
  sdk: ">=2.15.1 <3.0.0"
dev_dependencies:
  test: ^1.20.1
